# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg-headless,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "019wc30rbi2zbxkc3vzzkw3fayd3z7x0k396w2lnc9xcb9mv851i";
    aarch64-linux = "0yz6cbs1prvsc2xmkkn3dkvw3z7sp5qlwrawn815an45diag4k7i";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MrEhbr/yokoku/releases/download/v0.4.0/yokoku_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/MrEhbr/yokoku/releases/download/v0.4.0/yokoku_Linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "yokoku";
  version = "0.4.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin $out/share/yokoku
    cp -v ./yokoku $out/bin/yokoku
    cp -vr ./public $out/share/yokoku/public
    wrapProgram $out/bin/yokoku \
    --prefix PATH : ${lib.makeBinPath [ ffmpeg-headless ]} \
    --set-default DIOXUS_PUBLIC_PATH $out/share/yokoku/public
    runHook postInstall
  '';

  meta = {
    description = "Self-hosted manager for a movie and TV library";
    homepage = "https://github.com/MrEhbr/yokoku";
    license = lib.licenses.mit;
    mainProgram = "yokoku";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
