# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  ffmpeg-headless,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0qjd1pqlqwicrzi3xkkafhh951ypgsdwny72l0s371xdhkg5hhpn";
    aarch64-linux = "0yaz4c3q8nfnf2af5c6x6bdwbsy9nj2qz5ychki3sr06bkbpgnar";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MrEhbr/yokoku/releases/download/v0.6.1/yokoku_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/MrEhbr/yokoku/releases/download/v0.6.1/yokoku_Linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "yokoku";
  version = "0.6.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin $out/share/yokoku
    cp -v ./yokoku $out/bin/yokoku
    cp -vr ./public $out/share/yokoku/public
    wrapProgram $out/bin/yokoku \
    --prefix PATH : ${lib.makeBinPath [ ffmpeg-headless ]} \
    --set-default DIOXUS_PUBLIC_PATH $out/share/yokoku/public
    runHook postInstall
  '';

  meta = {
    description = "Self-hosted manager for a movie and TV library";
    homepage = "https://github.com/MrEhbr/yokoku";
    license = lib.licenses.mit;
    mainProgram = "yokoku";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
